! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module thrustacc
 use, intrinsic :: ISO_C_BINDING
 use openacc 
 implicit none
 private

 ! PUBLIC METHODS AND TYPES

type, bind(C) :: SwigDevArrayWrapper
  type(C_DEVPTR), public :: data = C_NULL_DEVPTR
  integer(C_SIZE_T), public :: size = 0
end type

 public :: sort
 interface sort
  module procedure sort__SWIG_0, sort__SWIG_1, sort__SWIG_2
 end interface

 ! WRAPPER DECLARATIONS
 interface
subroutine swigc_sort__SWIG_0(farg1) &
bind(C, name="_wrap_sort__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: SwigDevArrayWrapper
type(SwigDevArrayWrapper) :: farg1
end subroutine

subroutine swigc_sort__SWIG_1(farg1) &
bind(C, name="_wrap_sort__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: SwigDevArrayWrapper
type(SwigDevArrayWrapper) :: farg1
end subroutine

subroutine swigc_sort__SWIG_2(farg1) &
bind(C, name="_wrap_sort__SWIG_2")
use, intrinsic :: ISO_C_BINDING
import :: SwigDevArrayWrapper
type(SwigDevArrayWrapper) :: farg1
end subroutine

 end interface


contains
 ! FORTRAN PROXY CODE
subroutine sort__SWIG_0(data)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), dimension(:) :: data
type(SwigDevArrayWrapper) :: farg1 

farg1%data = acc_deviceptr(data)
farg1%size = size(data)
call swigc_sort__SWIG_0(farg1)
end subroutine

subroutine sort__SWIG_1(data)
use, intrinsic :: ISO_C_BINDING
real(C_FLOAT), dimension(:) :: data
type(SwigDevArrayWrapper) :: farg1 

farg1%data = acc_deviceptr(data)
farg1%size = size(data)
call swigc_sort__SWIG_1(farg1)
end subroutine

subroutine sort__SWIG_2(data)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:) :: data
type(SwigDevArrayWrapper) :: farg1 

farg1%data = acc_deviceptr(data)
farg1%size = size(data)
call swigc_sort__SWIG_2(farg1)
end subroutine


end module
