! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module thrustacc
 use, intrinsic :: ISO_C_BINDING
 use openacc 
 implicit none
 private

 ! PUBLIC METHODS AND TYPES

type, bind(C) :: SwigDevArrayWrapper
  type(C_DEVPTR), public :: data = C_NULL_DEVPTR
  integer(C_SIZE_T), public :: size = 0
end type

 public :: sort

 ! WRAPPER DECLARATIONS
 interface
subroutine swigc_sort(farg1) &
bind(C, name="_wrap_sort")
use, intrinsic :: ISO_C_BINDING
import :: SwigDevArrayWrapper
type(SwigDevArrayWrapper) :: farg1
end subroutine

 end interface


contains
 ! FORTRAN PROXY CODE
subroutine sort(data)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), dimension(:) :: data
type(SwigDevArrayWrapper) :: farg1 

farg1%data = acc_deviceptr(data)
farg1%size = size(data)
call swigc_sort(farg1)
end subroutine


end module
