;; This file was automatically generated by SWIG (http://www.swig.org).
;; Version 3.0.5
;;
;; Do not make changes to this file unless you know what you are doing--modify
;; the SWIG interface file instead.

(declare (unit foomod))

(declare 
    (hide swig-init swig-init-return)
    (foreign-declare "C_extern void swig_foomod_init(C_word,C_word,C_word) C_noret;"))
(define swig-init (##core#primitive "swig_foomod_init"))
(define swig-init-return (swig-init))



