/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <vector>
#include <stdexcept>

SWIGINTERN void std_vector_Sl_T_Sg__set(std::vector< T > *self,std::vector< T >::size_type i,std::vector< T >::value_type const &val){
    if (i < self->size())
    {
        (*self)[i] = val;
    }
    else
    {
        throw std::out_of_range("vector index out of range");
    }
}
#ifdef __cplusplus
extern "C" {
#endif
SWIGEXPORT  _wrap_new_Vec_Dbl__SWIG_0() {
  fresult = 0 ;
  std::vector< T > *result = 0 ;
  
  return fresult;
}


SWIGEXPORT  _wrap_Vec_Dbl_size() {
  fresult = 0 ;
  std::vector< T > *arg1 = (std::vector< T > *) 0 ;
  std::vector< T >::size_type result;
  
  return fresult;
}


SWIGEXPORT  _wrap_Vec_Dbl_capacity() {
  fresult = 0 ;
  std::vector< T > *arg1 = (std::vector< T > *) 0 ;
  std::vector< T >::size_type result;
  
  return fresult;
}


SWIGEXPORT void _wrap_Vec_Dbl_reserve() {
  std::vector< T > *arg1 = (std::vector< T > *) 0 ;
  std::vector< T >::size_type arg2 ;
  
  (arg1)->reserve(arg2);
}


SWIGEXPORT bool _wrap_Vec_Dbl_empty() {
  bool fresult = 0 ;
  std::vector< T > *arg1 = (std::vector< T > *) 0 ;
  bool result;
  
  result = (bool)((std::vector< T > const *)arg1)->empty();
  fresult = result; 
  return fresult;
}


SWIGEXPORT void _wrap_Vec_Dbl_clear() {
  std::vector< T > *arg1 = (std::vector< T > *) 0 ;
  
  (arg1)->clear();
}


SWIGEXPORT void _wrap_Vec_Dbl_push_back() {
  std::vector< T > *arg1 = (std::vector< T > *) 0 ;
  std::vector< T >::value_type *arg2 = 0 ;
  
  (arg1)->push_back((std::vector< T >::value_type const &)*arg2);
}


SWIGEXPORT  _wrap_Vec_Dbl_front() {
  fresult = 0 ;
  std::vector< T > *arg1 = (std::vector< T > *) 0 ;
  T *result = 0 ;
  
  return fresult;
}


SWIGEXPORT  _wrap_Vec_Dbl_back() {
  fresult = 0 ;
  std::vector< T > *arg1 = (std::vector< T > *) 0 ;
  T *result = 0 ;
  
  return fresult;
}


SWIGEXPORT void _wrap_Vec_Dbl_at() {
  std::vector< T > *arg1 = (std::vector< T > *) 0 ;
  std::vector< T >::size_type arg2 ;
  
  (arg1)->at(arg2);
}


SWIGEXPORT void _wrap_Vec_Dbl_set() {
  std::vector< T > *arg1 = (std::vector< T > *) 0 ;
  std::vector< T >::size_type arg2 ;
  std::vector< T >::value_type *arg3 = 0 ;
  
  std_vector_Sl_T_Sg__set(arg1,arg2,(T const &)*arg3);
}


SWIGEXPORT void _wrap_delete_Vec_Dbl() {
  std::vector< T > *arg1 = (std::vector< T > *) 0 ;
  
  delete arg1;
}


#ifdef __cplusplus
}
#endif

