! This file was automatically generated by SWIG (http://www.swig.org).
! Version 3.0.5
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module vec_I
 use, intrinsic :: ISO_C_BINDING
 interface
  function  &
 () &
 BIND(C,name="_wrap_")
  use,intrinsic :: ISO_C_BINDING
  implicit none
 end function
  function Vec_Dbl_size &
 () &
 BIND(C,name="_wrap_Vec_Dbl_size")
  use,intrinsic :: ISO_C_BINDING
  implicit none
 end function
  function Vec_Dbl_capacity &
 () &
 BIND(C,name="_wrap_Vec_Dbl_capacity")
  use,intrinsic :: ISO_C_BINDING
  implicit none
 end function
 subroutine Vec_Dbl_reserve &
 () &
 BIND(C,name="_wrap_Vec_Dbl_reserve")
  use,intrinsic :: ISO_C_BINDING
  implicit none
 end subroutine
 logical(C_BOOL) function Vec_Dbl_empty &
 () &
 BIND(C,name="_wrap_Vec_Dbl_empty")
  use,intrinsic :: ISO_C_BINDING
  implicit none
 end function
 subroutine Vec_Dbl_clear &
 () &
 BIND(C,name="_wrap_Vec_Dbl_clear")
  use,intrinsic :: ISO_C_BINDING
  implicit none
 end subroutine
 subroutine Vec_Dbl_push_back &
 () &
 BIND(C,name="_wrap_Vec_Dbl_push_back")
  use,intrinsic :: ISO_C_BINDING
  implicit none
 end subroutine
  function Vec_Dbl_front &
 () &
 BIND(C,name="_wrap_Vec_Dbl_front")
  use,intrinsic :: ISO_C_BINDING
  implicit none
 end function
  function Vec_Dbl_back &
 () &
 BIND(C,name="_wrap_Vec_Dbl_back")
  use,intrinsic :: ISO_C_BINDING
  implicit none
 end function
 subroutine Vec_Dbl_at &
 () &
 BIND(C,name="_wrap_Vec_Dbl_at")
  use,intrinsic :: ISO_C_BINDING
  implicit none
 end subroutine
 subroutine Vec_Dbl_set &
 () &
 BIND(C,name="_wrap_Vec_Dbl_set")
  use,intrinsic :: ISO_C_BINDING
  implicit none
 end subroutine
 subroutine delete_Vec_Dbl &
 () &
 BIND(C,name="_wrap_delete_Vec_Dbl")
  use,intrinsic :: ISO_C_BINDING
  implicit none
 end subroutine
 end interface
end module vec_I
