! This file was automatically generated by SWIG (http://www.swig.org).
! Version 3.0.5
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module vec_M
 use, intrinsic :: ISO_C_BINDING
 use vec_I
end module vec_M
