! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module simple_class
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! PUBLIC METHODS AND TYPES
 public :: DerpyStruct
 public :: print
 public :: multiply
 public :: makeone

 ! TYPES
 type, BIND(C) :: DerpyStruct
  integer(C_INT), public :: foo 
  real(C_DOUBLE), public :: bar
 end type


 ! WRAPPER DECLARATIONS
 interface
subroutine swigc_print(farg1) &
bind(C, name="swigc_print")
use, intrinsic :: ISO_C_BINDING
import :: DerpyStruct
type(DerpyStruct), intent(in) :: farg1
end subroutine

subroutine swigc_multiply(farg1) &
bind(C, name="swigc_multiply")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

function swigc_makeone(farg1) &
bind(C, name="swigc_makeone") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: DerpyStruct
integer(C_INT), intent(in) :: farg1
type(DerpyStruct) :: fresult
end function

 end interface


contains
 ! FORTRAN PROXY CODE
subroutine print(s)
use, intrinsic :: ISO_C_BINDING
type(DerpyStruct), intent(in) :: s
type(DerpyStruct) :: farg1 

farg1 = s
call swigc_print(farg1)
end subroutine

subroutine multiply(s)
use, intrinsic :: ISO_C_BINDING
type(DerpyStruct), target, intent(inout) :: s
type(C_PTR) :: farg1 

farg1 = c_loc(s)
call swigc_multiply(farg1)
end subroutine

function makeone(i) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
type(DerpyStruct) :: swigf_result
integer(C_INT), intent(in) :: i
type(DerpyStruct) :: fresult 
integer(C_INT) :: farg1 

farg1 = i
fresult = swigc_makeone(farg1)
swigf_result = fresult
end function


end module simple_class
