! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module pairtest
 use, intrinsic :: ISO_C_BINDING
 implicit none

 ! PUBLIC METHODS AND TYPES

type, public, bind(C) :: SwigfArrayWrapper
  type(C_PTR), public :: data
  integer(C_INT), public :: size
end type


type, public :: SwigfUnknownClass
  type(C_PTR), public :: swigptr
end type

 public :: do_something
 ! PARAMETERS

 ! TYPES

 ! WRAPPER DECLARATIONS
 private
 interface
function swigc_do_something() &
bind(C, name="swigc_do_something") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: fresult
end function

 end interface

contains
  ! FORTRAN PROXY CODE
function do_something() &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
type(SwigfUnknownClass) :: swigf_result
type(C_PTR) :: fresult 

fresult = swigc_do_something()
swigf_result%swigptr = fresult
end function

end module pairtest
