# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_vec', [dirname(__file__)])
        except ImportError:
            import _vec
            return _vec
        if fp is not None:
            try:
                _mod = imp.load_module('_vec', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _vec = swig_import_helper()
    del swig_import_helper
else:
    import _vec
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _vec.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _vec.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _vec.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _vec.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _vec.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _vec.SwigPyIterator_equal(self, x)

    def copy(self):
        return _vec.SwigPyIterator_copy(self)

    def next(self):
        return _vec.SwigPyIterator_next(self)

    def __next__(self):
        return _vec.SwigPyIterator___next__(self)

    def previous(self):
        return _vec.SwigPyIterator_previous(self)

    def advance(self, n):
        return _vec.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _vec.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _vec.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _vec.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _vec.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _vec.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _vec.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _vec.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Vec_Dbl(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Vec_Dbl, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Vec_Dbl, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _vec.Vec_Dbl_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _vec.Vec_Dbl___nonzero__(self)

    def __bool__(self):
        return _vec.Vec_Dbl___bool__(self)

    def __len__(self):
        return _vec.Vec_Dbl___len__(self)

    def pop(self):
        return _vec.Vec_Dbl_pop(self)

    def __getslice__(self, i, j):
        return _vec.Vec_Dbl___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _vec.Vec_Dbl___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _vec.Vec_Dbl___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _vec.Vec_Dbl___delitem__(self, *args)

    def __getitem__(self, *args):
        return _vec.Vec_Dbl___getitem__(self, *args)

    def __setitem__(self, *args):
        return _vec.Vec_Dbl___setitem__(self, *args)

    def append(self, x):
        return _vec.Vec_Dbl_append(self, x)

    def empty(self):
        return _vec.Vec_Dbl_empty(self)

    def size(self):
        return _vec.Vec_Dbl_size(self)

    def clear(self):
        return _vec.Vec_Dbl_clear(self)

    def swap(self, v):
        return _vec.Vec_Dbl_swap(self, v)

    def get_allocator(self):
        return _vec.Vec_Dbl_get_allocator(self)

    def begin(self):
        return _vec.Vec_Dbl_begin(self)

    def end(self):
        return _vec.Vec_Dbl_end(self)

    def rbegin(self):
        return _vec.Vec_Dbl_rbegin(self)

    def rend(self):
        return _vec.Vec_Dbl_rend(self)

    def pop_back(self):
        return _vec.Vec_Dbl_pop_back(self)

    def erase(self, *args):
        return _vec.Vec_Dbl_erase(self, *args)

    def __init__(self, *args):
        this = _vec.new_Vec_Dbl(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _vec.Vec_Dbl_push_back(self, x)

    def front(self):
        return _vec.Vec_Dbl_front(self)

    def back(self):
        return _vec.Vec_Dbl_back(self)

    def assign(self, n, x):
        return _vec.Vec_Dbl_assign(self, n, x)

    def resize(self, *args):
        return _vec.Vec_Dbl_resize(self, *args)

    def insert(self, *args):
        return _vec.Vec_Dbl_insert(self, *args)

    def reserve(self, n):
        return _vec.Vec_Dbl_reserve(self, n)

    def capacity(self):
        return _vec.Vec_Dbl_capacity(self)
    __swig_destroy__ = _vec.delete_Vec_Dbl
    __del__ = lambda self: None
Vec_Dbl_swigregister = _vec.Vec_Dbl_swigregister
Vec_Dbl_swigregister(Vec_Dbl)

# This file is compatible with both classic and new-style classes.


