/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class foomod {
  public static void set_something(int x, double y) {
    foomodJNI.set_something(x, y);
  }

  public static double get_something(int x) {
    return foomodJNI.get_something(x);
  }

}
