! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module kokkos
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! PUBLIC METHODS AND TYPES
 public :: c_kokkos_initialize_with_args
 public :: c_kokkos_initialize
 public :: c_kokkos_finalize
 public :: c_kokkos_daxpy
 public :: c_kokkos_allocate_A
 public :: c_kokkos_allocate_1i
 public :: c_kokkos_allocate_1d
 public :: c_kokkos_allocate_2d
 public :: c_kokkos_allocate_3d
 public :: c_kokkos_allocate_4d
 public :: c_kokkos_allocate_5d
 public :: c_kokkos_allocate_6d
 public :: c_kokkos_allocate_7d
 public :: c_kokkos_free_1d
 public :: c_kokkos_free_2d
 public :: c_kokkos_free_4d

 ! WRAPPER DECLARATIONS
 interface
subroutine c_kokkos_initialize_with_args(argc, argv) &
bind(C, name="c_kokkos_initialize_with_args")
use, intrinsic :: ISO_C_BINDING
integer(C_INT), value :: argc
type(C_PTR), value :: argv
end subroutine

subroutine c_kokkos_initialize() &
bind(C, name="c_kokkos_initialize")
use, intrinsic :: ISO_C_BINDING
end subroutine

subroutine c_kokkos_finalize() &
bind(C, name="c_kokkos_finalize")
use, intrinsic :: ISO_C_BINDING
end subroutine

subroutine c_kokkos_daxpy(n, a, x, y) &
bind(C, name="c_kokkos_daxpy")
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: n
real(C_DOUBLE), intent(in) :: a
real(C_DOUBLE), intent(in) :: x
real(C_DOUBLE) :: y
end subroutine

subroutine c_kokkos_allocate_A(m, n, raw_a, v_a) &
bind(C, name="c_kokkos_allocate_A")
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: m
integer(C_INT), intent(in) :: n
type(C_PTR), value :: raw_a

end subroutine

subroutine c_kokkos_allocate_1i(m, a, v_a, a_name) &
bind(C, name="c_kokkos_allocate_1i")
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: m
type(C_PTR), value :: a
type(C_PTR), value :: v_a
character(C_CHAR), intent(in) :: a_name
end subroutine

subroutine c_kokkos_allocate_1d(m, a, v_a, a_name) &
bind(C, name="c_kokkos_allocate_1d")
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: m
type(C_PTR), value :: a
type(C_PTR), value :: v_a
character(C_CHAR), intent(in) :: a_name
end subroutine

subroutine c_kokkos_allocate_2d(m, n, a, v_a, a_name) &
bind(C, name="c_kokkos_allocate_2d")
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: m
integer(C_INT), intent(in) :: n
type(C_PTR), value :: a
type(C_PTR), value :: v_a
character(C_CHAR), intent(in) :: a_name
end subroutine

subroutine c_kokkos_allocate_3d(m, n, o, a, v_a, a_name) &
bind(C, name="c_kokkos_allocate_3d")
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: m
integer(C_INT), intent(in) :: n
integer(C_INT), intent(in) :: o
type(C_PTR), value :: a
type(C_PTR), value :: v_a
character(C_CHAR), intent(in) :: a_name
end subroutine

subroutine c_kokkos_allocate_4d(m, n, o, p, a, v_a, a_name) &
bind(C, name="c_kokkos_allocate_4d")
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: m
integer(C_INT), intent(in) :: n
integer(C_INT), intent(in) :: o
integer(C_INT), intent(in) :: p
type(C_PTR), value :: a
type(C_PTR), value :: v_a
character(C_CHAR), intent(in) :: a_name
end subroutine

subroutine c_kokkos_allocate_5d(m, n, o, p, q, a, v_a, a_name) &
bind(C, name="c_kokkos_allocate_5d")
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: m
integer(C_INT), intent(in) :: n
integer(C_INT), intent(in) :: o
integer(C_INT), intent(in) :: p
integer(C_INT), intent(in) :: q
type(C_PTR), value :: a
type(C_PTR), value :: v_a
character(C_CHAR), intent(in) :: a_name
end subroutine

subroutine c_kokkos_allocate_6d(m, n, o, p, q, r, a, v_a, a_name) &
bind(C, name="c_kokkos_allocate_6d")
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: m
integer(C_INT), intent(in) :: n
integer(C_INT), intent(in) :: o
integer(C_INT), intent(in) :: p
integer(C_INT), intent(in) :: q
integer(C_INT), intent(in) :: r
type(C_PTR), value :: a
type(C_PTR), value :: v_a
character(C_CHAR), intent(in) :: a_name
end subroutine

subroutine c_kokkos_allocate_7d(m, n, o, p, q, r, s, a, v_a, a_name) &
bind(C, name="c_kokkos_allocate_7d")
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: m
integer(C_INT), intent(in) :: n
integer(C_INT), intent(in) :: o
integer(C_INT), intent(in) :: p
integer(C_INT), intent(in) :: q
integer(C_INT), intent(in) :: r
integer(C_INT), intent(in) :: s
type(C_PTR), value :: a
type(C_PTR), value :: v_a
character(C_CHAR), intent(in) :: a_name
end subroutine

subroutine c_kokkos_free_1d(v_a) &
bind(C, name="c_kokkos_free_1d")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: v_a
end subroutine

subroutine c_kokkos_free_2d(v_a) &
bind(C, name="c_kokkos_free_2d")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: v_a
end subroutine

subroutine c_kokkos_free_4d(v_a) &
bind(C, name="c_kokkos_free_4d")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: v_a
end subroutine

 end interface


end module
