<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('foomod')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_foomod.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('foomod.so')) return;
    } else {
      if (!dl('foomod.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class foomod {
	static function set_something($x,$y) {
		set_something($x,$y);
	}

	static function get_something($x) {
		return get_something($x);
	}
}

/* PHP Proxy Classes */

?>
