/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_FOOMOD_H
#define PHP_FOOMOD_H

extern zend_module_entry foomod_module_entry;
#define phpext_foomod_ptr &foomod_module_entry

#ifdef PHP_WIN32
# define PHP_FOOMOD_API __declspec(dllexport)
#else
# define PHP_FOOMOD_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(foomod);
PHP_MSHUTDOWN_FUNCTION(foomod);
PHP_RINIT_FUNCTION(foomod);
PHP_RSHUTDOWN_FUNCTION(foomod);
PHP_MINFO_FUNCTION(foomod);

ZEND_NAMED_FUNCTION(_wrap_set_something);
ZEND_NAMED_FUNCTION(_wrap_get_something);
#endif /* PHP_FOOMOD_H */
