/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class vecJNI {
  public final static native long new_Vec_Dbl__SWIG_0();
  public final static native long new_Vec_Dbl__SWIG_1(long jarg1);
  public final static native long Vec_Dbl_size(long jarg1);
  public final static native long Vec_Dbl_capacity(long jarg1);
  public final static native void Vec_Dbl_reserve(long jarg1, long jarg2);
  public final static native boolean Vec_Dbl_isEmpty(long jarg1);
  public final static native void Vec_Dbl_clear(long jarg1);
  public final static native void Vec_Dbl_add(long jarg1, long jarg2);
  public final static native long Vec_Dbl_get(long jarg1, int jarg2);
  public final static native void Vec_Dbl_set(long jarg1, int jarg2, long jarg3);
  public final static native void delete_Vec_Dbl(long jarg1);
}
