! This file was automatically generated by SWIG (http://www.swig.org).
! Version 3.0.5
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module foomod_I
 use, intrinsic :: ISO_C_BINDING
 interface
 subroutine set_something &
 (farg1, farg2) &
 BIND(C,name="_wrap_set_something")
  use,intrinsic :: ISO_C_BINDING
  implicit none
  integer(C_INT) :: farg1;
  real(C_DOUBLE) :: farg2;
 end subroutine
 real(C_DOUBLE) function get_something &
 (farg1) &
 BIND(C,name="_wrap_get_something")
  use,intrinsic :: ISO_C_BINDING
  implicit none
  integer(C_INT) :: farg1;
 end function
 end interface
end module foomod_I
