! This file was automatically generated by SWIG (http://www.swig.org).
! Version 3.0.5
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module foomod_M
 use, intrinsic :: ISO_C_BINDING
 use foomod_I
 implicit none
 ! TYPES
 ! INTERFACES
contains
   subroutine set_something(farg1, farg2)
    use, intrinsic :: ISO_C_BINDING
    implicit none
    integer(C_INT) :: farg1
    real(C_DOUBLE) :: farg2
   end subroutine
   function get_something(farg1) &
      result(fresult)
    use, intrinsic :: ISO_C_BINDING
    implicit none
    real(C_DOUBLE) :: fresult
    integer(C_INT) :: farg1
   end function
end module foomod_M
