! This file was automatically generated by SWIG (http://www.swig.org).
! Version 3.0.11
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module foomod
 use, intrinsic :: ISO_C_BINDING
 implicit none
 ! PUBLIC METHODS AND TYPES
 public :: set_something
 public :: get_something
 public :: get_something_ref
 public :: get_something_ptr
 ! TYPES
 ! INTERFACES
 private
 interface
   subroutine set_something(farg1, farg2) &
      bind(C, name="swigc_set_something")
    use, intrinsic :: ISO_C_BINDING
    implicit none
    integer(C_INT) :: farg1
    real(C_DOUBLE) :: farg2
   end subroutine
   function get_something(farg1) &
      result(fresult) &
      bind(C, name="swigc_get_something")
    use, intrinsic :: ISO_C_BINDING
    implicit none
    real(C_DOUBLE) :: fresult
    integer(C_INT) :: farg1
   end function
   subroutine get_something_ref(farg1, farg2) &
      bind(C, name="swigc_get_something_ref")
    use, intrinsic :: ISO_C_BINDING
    implicit none
    integer(C_INT) :: farg1
    real(C_DOUBLE) :: farg2
   end subroutine
   subroutine get_something_ptr(farg1, farg2) &
      bind(C, name="swigc_get_something_ptr")
    use, intrinsic :: ISO_C_BINDING
    implicit none
    integer(C_INT) :: farg1
    real(C_DOUBLE) :: farg2
   end subroutine
 end interface
contains
end module foomod
