! This file was automatically generated by SWIG (http://www.swig.org).
! Version 3.0.5
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module foomod_M
 use, intrinsic :: ISO_C_BINDING
 use foomod_I
end module foomod_M
