! This file was automatically generated by SWIG (http://www.swig.org).
! Version 3.0.11
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module foomod
 use, intrinsic :: ISO_C_BINDING
 implicit none
 ! List of public interface functions
 public :: set_something
 public :: get_something
 ! TYPES
 ! INTERFACES
 private
 interface
   subroutine set_something(farg1, farg2) &
      bind(C, name="swigc_set_something")
    use, intrinsic :: ISO_C_BINDING
    implicit none
    integer(C_INT) :: farg1
    real(C_DOUBLE) :: farg2
   end subroutine
   function get_something(farg1) &
      result(fresult) &
      bind(C, name="swigc_get_something")
    use, intrinsic :: ISO_C_BINDING
    implicit none
    real(C_DOUBLE) :: fresult
    integer(C_INT) :: farg1
   end function
 end interface
end module foomod
