/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class vecJNI {
  public final static native long new_vector__SWIG_0();
  public final static native long new_vector__SWIG_1(long jarg1, double jarg2);
  public final static native long new_vector__SWIG_2(long jarg1);
  public final static native boolean vector_empty(long jarg1, vector jarg1_);
  public final static native long vector_size(long jarg1, vector jarg1_);
  public final static native double vector_get(long jarg1, vector jarg1_, long jarg2);
  public final static native void vector_set(long jarg1, vector jarg1_, long jarg2, double jarg3);
  public final static native void delete_vector(long jarg1);
  public final static native void do_something(long jarg1, vector jarg1_);
}
