/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class vector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        vecJNI.delete_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vector() {
    this(vecJNI.new_vector__SWIG_0(), true);
  }

  public vector(long count, double fillval) {
    this(vecJNI.new_vector__SWIG_1(count, fillval), true);
  }

  public vector(long count) {
    this(vecJNI.new_vector__SWIG_2(count), true);
  }

  public boolean empty() {
    return vecJNI.vector_empty(swigCPtr, this);
  }

  public long size() {
    return vecJNI.vector_size(swigCPtr, this);
  }

  public double get(long index) {
    return vecJNI.vector_get(swigCPtr, this, index);
  }

  public void set(long index, double value) {
    vecJNI.vector_set(swigCPtr, this, index, value);
  }

}
