! This file was automatically generated by SWIG (http://www.swig.org).
! Version 3.0.5
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module vec_I
 use, intrinsic :: ISO_C_BINDING
 implicit none
 interface
   subroutine _wrap_do_something() &
      bind(C, name="_wrap_do_something")
    use, intrinsic :: ISO_C_BINDING
    implicit none
   end subroutine
   function _wrap_new_Vec_Dbl__SWIG_0() &
      result(fresult) &
      bind(C, name="_wrap_new_Vec_Dbl__SWIG_0")
    use, intrinsic :: ISO_C_BINDING
    implicit none
     :: fresult
   end function
   function _wrap_Vec_Dbl_empty() &
      result(fresult) &
      bind(C, name="_wrap_Vec_Dbl_empty")
    use, intrinsic :: ISO_C_BINDING
    implicit none
    logical(C_BOOL) :: fresult
   end function
   function _wrap_Vec_Dbl_size() &
      result(fresult) &
      bind(C, name="_wrap_Vec_Dbl_size")
    use, intrinsic :: ISO_C_BINDING
    implicit none
    integer(C_LONG) :: fresult
   end function
   function _wrap_Vec_Dbl_get(farg1farg1) &
      result(fresult) &
      bind(C, name="_wrap_Vec_Dbl_get")
    use, intrinsic :: ISO_C_BINDING
    implicit none
    real(C_DOUBLE) :: fresult
     :: farg1
   end function
   subroutine _wrap_Vec_Dbl_set(farg1farg1) &
      bind(C, name="_wrap_Vec_Dbl_set")
    use, intrinsic :: ISO_C_BINDING
    implicit none
     :: farg1
   end subroutine
   subroutine _wrap_delete_Vec_Dbl() &
      bind(C, name="_wrap_delete_Vec_Dbl")
    use, intrinsic :: ISO_C_BINDING
    implicit none
   end subroutine
 end interface
end module vec_I
