! This file was automatically generated by SWIG (http://www.swig.org).
! Version 3.0.5
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module vec_M
 use, intrinsic :: ISO_C_BINDING
 use vec_I
 implicit none
 ! TYPES
 type Vec_Dbl
  type(C_PTR), private :: ptr = C_NULL_PTR
 contains
 end type
 ! INTERFACES
contains
   subroutine do_something()
    use, intrinsic :: ISO_C_BINDING
    implicit none
   end subroutine
   function new_Vec_Dbl__SWIG_0() &
      result(fresult)
    use, intrinsic :: ISO_C_BINDING
    implicit none
     :: fresult
   end function
   function Vec_Dbl_empty() &
      result(fresult)
    use, intrinsic :: ISO_C_BINDING
    implicit none
    logical(C_BOOL) :: fresult
   end function
   function Vec_Dbl_size() &
      result(fresult)
    use, intrinsic :: ISO_C_BINDING
    implicit none
    integer(C_LONG) :: fresult
   end function
   function Vec_Dbl_get(farg1farg1) &
      result(fresult)
    use, intrinsic :: ISO_C_BINDING
    implicit none
    real(C_DOUBLE) :: fresult
     :: farg1
   end function
   subroutine Vec_Dbl_set(farg1farg1)
    use, intrinsic :: ISO_C_BINDING
    implicit none
     :: farg1
   end subroutine
   subroutine delete_Vec_Dbl()
    use, intrinsic :: ISO_C_BINDING
    implicit none
   end subroutine
end module vec_M
