!>
!! This file has been dynamically generated by Class Interface Xml (CIX) 
!! DO NOT MODIFY THIS FILE -- CHANGES WILL BE OVERWRITTEN UPON REGENERATION
!! If changes need to occur, modify the appropriate CIX xml file
!! Date Generated: LET VERSION CONTROL TRACK
!! If any issues are experiences with this generated file that cannot be fixed
!! with adjustment of the CIX xml file, please contact Robert A. Lefebvre, raq@ornl.gov
!!/
module ScaleSTL_Vec_Dbl_M
use, intrinsic :: ISO_C_BINDING
use ScaleSTL_Vec_Dbl_I
type ScaleSTL_Vec_Dbl
    type(C_PTR) :: instance_ptr=C_NULL_PTR
    contains
    procedure, pass(this) :: initialize_size => ScaleSTL_Vec_Dbl_initialize_size
    procedure, pass(this) :: initialize_from => ScaleSTL_Vec_Dbl_initialize_from
    procedure, pass(this) :: size => ScaleSTL_Vec_Dbl_size
    procedure, pass(this) :: element_length => ScaleSTL_Vec_Dbl_element_length
    procedure, pass(this) :: total_element_length => ScaleSTL_Vec_Dbl_total_element_length
    procedure, pass(this) :: max_element_length => ScaleSTL_Vec_Dbl_max_element_length
    procedure, pass(this) :: resize => ScaleSTL_Vec_Dbl_resize
    procedure, pass(this) :: reserve => ScaleSTL_Vec_Dbl_reserve
    procedure, pass(this) :: resize_fill => ScaleSTL_Vec_Dbl_resize_fill
    procedure, pass(this) :: empty => ScaleSTL_Vec_Dbl_empty
    procedure, pass(this) :: at => ScaleSTL_Vec_Dbl_at
    procedure, pass(this) :: set => ScaleSTL_Vec_Dbl_set
    procedure, pass(this) :: front => ScaleSTL_Vec_Dbl_front
    procedure, pass(this) :: back => ScaleSTL_Vec_Dbl_back
    procedure, pass(this) :: push_back => ScaleSTL_Vec_Dbl_push_back
    procedure, pass(this) :: pop_back => ScaleSTL_Vec_Dbl_pop_back
    procedure, pass(this) :: insert => ScaleSTL_Vec_Dbl_insert
    procedure, pass(this) :: erase => ScaleSTL_Vec_Dbl_erase
    procedure, pass(this) :: contains => ScaleSTL_Vec_Dbl_contains
    procedure, pass(this) :: clear => ScaleSTL_Vec_Dbl_clear
    procedure, pass(this) :: initialize => ScaleSTL_Vec_Dbl_initialize
    procedure, pass(this) :: destroy => ScaleSTL_Vec_Dbl_destroy
end type ScaleSTL_Vec_Dbl
contains
subroutine ScaleSTL_Vec_Dbl_initialize_size(this, size)
    implicit none
    class(ScaleSTL_Vec_Dbl) :: this
    integer(C_INT)::size
    this%instance_ptr = f_ScaleSTL_Vec_Dbl_initialize_size( size)
end subroutine
subroutine ScaleSTL_Vec_Dbl_initialize_from(this, orig)
    implicit none
    class(ScaleSTL_Vec_Dbl) :: this
    class(ScaleSTL_Vec_Dbl)::orig
    this%instance_ptr = f_ScaleSTL_Vec_Dbl_initialize_from( orig%instance_ptr)
end subroutine
function ScaleSTL_Vec_Dbl_size(this) result(result2Return)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    integer(C_INT):: result2Return
    result2Return=f_ScaleSTL_Vec_Dbl_size(this%instance_ptr)
end function
function ScaleSTL_Vec_Dbl_element_length(this, index) result(result2Return)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    integer(C_INT)::index
    integer(C_INT):: result2Return
    result2Return=f_ScaleSTL_Vec_Dbl_element_length(this%instance_ptr, index-1)
end function
function ScaleSTL_Vec_Dbl_total_element_length(this) result(result2Return)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    integer(C_INT):: result2Return
    result2Return=f_ScaleSTL_Vec_Dbl_total_element_length(this%instance_ptr)
end function
function ScaleSTL_Vec_Dbl_max_element_length(this) result(result2Return)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    integer(C_INT):: result2Return
    result2Return=f_ScaleSTL_Vec_Dbl_max_element_length(this%instance_ptr)
end function
subroutine ScaleSTL_Vec_Dbl_resize(this, newSize)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    integer(C_INT)::newSize
    call f_ScaleSTL_Vec_Dbl_resize(this%instance_ptr, newSize)
end subroutine
subroutine ScaleSTL_Vec_Dbl_reserve(this, maxSize)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    integer(C_INT)::maxSize
    call f_ScaleSTL_Vec_Dbl_reserve(this%instance_ptr, maxSize)
end subroutine
subroutine ScaleSTL_Vec_Dbl_resize_fill(this, newSize, fill)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    integer(C_INT)::newSize
    real(C_DOUBLE)::fill
    call f_ScaleSTL_Vec_Dbl_resize_fill(this%instance_ptr, newSize,fill)
end subroutine
function ScaleSTL_Vec_Dbl_empty(this) result(result2Return)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    logical(C_BOOL):: result2Return
    result2Return=f_ScaleSTL_Vec_Dbl_empty(this%instance_ptr)
end function
function ScaleSTL_Vec_Dbl_at(this, index) result(result2Return)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    integer(C_INT)::index
    real(C_DOUBLE):: result2Return
    result2Return=f_ScaleSTL_Vec_Dbl_at(this%instance_ptr, index-1)
end function
subroutine ScaleSTL_Vec_Dbl_set(this, index, value)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    integer(C_INT)::index
    real(C_DOUBLE)::value
    call f_ScaleSTL_Vec_Dbl_set(this%instance_ptr, index-1,value)
end subroutine
function ScaleSTL_Vec_Dbl_front(this) result(result2Return)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    real(C_DOUBLE):: result2Return
    result2Return=f_ScaleSTL_Vec_Dbl_front(this%instance_ptr)
end function
function ScaleSTL_Vec_Dbl_back(this) result(result2Return)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    real(C_DOUBLE):: result2Return
    result2Return=f_ScaleSTL_Vec_Dbl_back(this%instance_ptr)
end function
subroutine ScaleSTL_Vec_Dbl_push_back(this, newValue)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    real(C_DOUBLE)::newValue
    call f_ScaleSTL_Vec_Dbl_push_back(this%instance_ptr, newValue)
end subroutine
subroutine ScaleSTL_Vec_Dbl_pop_back(this)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    call f_ScaleSTL_Vec_Dbl_pop_back(this%instance_ptr)
end subroutine
subroutine ScaleSTL_Vec_Dbl_insert(this, index, item)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    integer(C_INT)::index
    real(C_DOUBLE)::item
    call f_ScaleSTL_Vec_Dbl_insert(this%instance_ptr, index-1,item)
end subroutine
subroutine ScaleSTL_Vec_Dbl_erase(this, index)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    integer(C_INT)::index
    call f_ScaleSTL_Vec_Dbl_erase(this%instance_ptr, index-1)
end subroutine
function ScaleSTL_Vec_Dbl_contains(this, item) result(result2Return)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    real(C_DOUBLE)::item
    logical(C_BOOL):: result2Return
    result2Return=f_ScaleSTL_Vec_Dbl_contains(this%instance_ptr, item)
end function
subroutine ScaleSTL_Vec_Dbl_clear(this)
    implicit none
    class(ScaleSTL_Vec_Dbl)::this
    call f_ScaleSTL_Vec_Dbl_clear(this%instance_ptr)
end subroutine
subroutine ScaleSTL_Vec_Dbl_initialize(this)
    implicit none
    class(ScaleSTL_Vec_Dbl) :: this
    this%instance_ptr = f_ScaleSTL_Vec_Dbl_initialize()
end subroutine
subroutine ScaleSTL_Vec_Dbl_destroy(this)
    implicit none
    class(ScaleSTL_Vec_Dbl) :: this
    call f_ScaleSTL_Vec_Dbl_destroy(this%instance_ptr)
    this%instance_ptr = C_NULL_PTR
end subroutine
end module ScaleSTL_Vec_Dbl_M
