!>
!! This file has been dynamically generated by Class Interface Xml (CIX) 
!! DO NOT MODIFY THIS FILE -- CHANGES WILL BE OVERWRITTEN UPON REGENERATION
!! If changes need to occur, modify the appropriate CIX xml file
!! Date Generated: LET VERSION CONTROL TRACK
!! If any issues are experiences with this generated file that cannot be fixed
!! with adjustment of the CIX xml file, please contact Robert A. Lefebvre, raq@ornl.gov
!!/
module ScaleSTL_Vec_Dbl_I
use, intrinsic :: ISO_C_BINDING
interface
type(C_PTR) function f_ScaleSTL_Vec_Dbl_initialize_size&
( size )&
BIND(C,name="ScaleSTL_Vec_Dbl_initialize_size")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR) :: ScaleSTL_Vec_Dbl_ptr;
    integer(C_SIZE_T) :: size;
end function
type(C_PTR) function f_ScaleSTL_Vec_Dbl_initialize_copy&
( orig )&
BIND(C,name="ScaleSTL_Vec_Dbl_initialize_copy")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR) :: ScaleSTL_Vec_Dbl_ptr;
    type(C_PTR), value :: orig;
end function
integer(C_SIZE_T) function f_ScaleSTL_Vec_Dbl_size&
(ScaleSTL_Vec_Dbl_ptr ) &
BIND(C,name="ScaleSTL_Vec_Dbl_size")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
end function
integer(C_SIZE_T) function f_ScaleSTL_Vec_Dbl_element_length&
(ScaleSTL_Vec_Dbl_ptr, index ) &
BIND(C,name="ScaleSTL_Vec_Dbl_element_length")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
    integer(C_SIZE_T) :: index;
end function
integer(C_SIZE_T) function f_ScaleSTL_Vec_Dbl_total_element_length&
(ScaleSTL_Vec_Dbl_ptr ) &
BIND(C,name="ScaleSTL_Vec_Dbl_total_element_length")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
end function
integer(C_SIZE_T) function f_ScaleSTL_Vec_Dbl_max_element_length&
(ScaleSTL_Vec_Dbl_ptr ) &
BIND(C,name="ScaleSTL_Vec_Dbl_max_element_length")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
end function
subroutine f_ScaleSTL_Vec_Dbl_resize&
(ScaleSTL_Vec_Dbl_ptr, newSize ) &
BIND(C,name="ScaleSTL_Vec_Dbl_resize")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
    integer(C_SIZE_T) :: newSize;
end subroutine
subroutine f_ScaleSTL_Vec_Dbl_reserve&
(ScaleSTL_Vec_Dbl_ptr, maxSize ) &
BIND(C,name="ScaleSTL_Vec_Dbl_reserve")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
    integer(C_SIZE_T) :: maxSize;
end subroutine
subroutine f_ScaleSTL_Vec_Dbl_resize_fill&
(ScaleSTL_Vec_Dbl_ptr, newSize,fill ) &
BIND(C,name="ScaleSTL_Vec_Dbl_resize_fill")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
    integer(C_SIZE_T) :: newSize;
    real(C_DOUBLE) :: fill;
end subroutine
logical(C_BOOL) function f_ScaleSTL_Vec_Dbl_empty&
(ScaleSTL_Vec_Dbl_ptr ) &
BIND(C,name="ScaleSTL_Vec_Dbl_empty")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
end function
real(C_DOUBLE) function f_ScaleSTL_Vec_Dbl_at&
(ScaleSTL_Vec_Dbl_ptr, index ) &
BIND(C,name="ScaleSTL_Vec_Dbl_at")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
    integer(C_SIZE_T) :: index;
end function
subroutine f_ScaleSTL_Vec_Dbl_set&
(ScaleSTL_Vec_Dbl_ptr, index,value ) &
BIND(C,name="ScaleSTL_Vec_Dbl_set")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
    integer(C_SIZE_T) :: index;
    real(C_DOUBLE) :: value;
end subroutine
real(C_DOUBLE) function f_ScaleSTL_Vec_Dbl_front&
(ScaleSTL_Vec_Dbl_ptr ) &
BIND(C,name="ScaleSTL_Vec_Dbl_front")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
end function
real(C_DOUBLE) function f_ScaleSTL_Vec_Dbl_back&
(ScaleSTL_Vec_Dbl_ptr ) &
BIND(C,name="ScaleSTL_Vec_Dbl_back")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
end function
subroutine f_ScaleSTL_Vec_Dbl_push_back&
(ScaleSTL_Vec_Dbl_ptr, newValue ) &
BIND(C,name="ScaleSTL_Vec_Dbl_push_back")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
    real(C_DOUBLE) :: newValue;
end subroutine
subroutine f_ScaleSTL_Vec_Dbl_pop_back&
(ScaleSTL_Vec_Dbl_ptr ) &
BIND(C,name="ScaleSTL_Vec_Dbl_pop_back")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
end subroutine
subroutine f_ScaleSTL_Vec_Dbl_insert&
(ScaleSTL_Vec_Dbl_ptr, index,item ) &
BIND(C,name="ScaleSTL_Vec_Dbl_insert")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
    integer(C_SIZE_T) :: index;
    real(C_DOUBLE) :: item;
end subroutine
subroutine f_ScaleSTL_Vec_Dbl_erase&
(ScaleSTL_Vec_Dbl_ptr, index ) &
BIND(C,name="ScaleSTL_Vec_Dbl_erase")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
    integer(C_SIZE_T) :: index;
end subroutine
logical(C_BOOL) function f_ScaleSTL_Vec_Dbl_contains&
(ScaleSTL_Vec_Dbl_ptr, item ) &
BIND(C,name="ScaleSTL_Vec_Dbl_contains")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
    real(C_DOUBLE) :: item;
end function
subroutine f_ScaleSTL_Vec_Dbl_clear&
(ScaleSTL_Vec_Dbl_ptr ) &
BIND(C,name="ScaleSTL_Vec_Dbl_clear")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: ScaleSTL_Vec_Dbl_ptr;
end subroutine
type(C_PTR) function f_ScaleSTL_Vec_Dbl_initialize&
( )&
BIND(C,name="ScaleSTL_Vec_Dbl_initialize")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR) :: ScaleSTL_Vec_Dbl_ptr;
end function
subroutine f_ScaleSTL_Vec_Dbl_destroy&
(this) &
BIND(C,name="ScaleSTL_Vec_Dbl_destroy")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: this;
end subroutine
end interface
end module ScaleSTL_Vec_Dbl_I
