
# failed to compile fortran
abstract_signature \
  abstract_typedef2 \
  allprotected \
  array_member \
  array_typedef_memberin \
  arrayref \
  arrays_global \
  arrays_global_twodim \
  arrays_scope \
  bloody_hell \
  bools \
  char_binary \
  char_strings \
  class_ignore \
  class_scope_weird \
  clientdata_prop_a \
  clientdata_prop_b \
  constructor_copy \
  constructor_explicit \
  conversion_ns_template \
  cpp_namespace \
  cpp_nodefault \
  cpp_typedef \
  derived_nested \
  director_classes \
  director_default \
  director_detect \
  director_frob \
  director_ignore \
  director_keywords \
  director_nested \
  director_nspace \
  director_overload2 \
  director_protected \
  director_redefined \
  director_string \
  director_wombat \
  enum_scope_template \
  evil_diamond_prop \
  extend_default \
  extend_special_variables \
  extern_c \
  features \
  friends \
  friends_template \
  fvirtual \
  ignore_parameter \
  ignore_template_constructor \
  import_stl_b \
  imports_a \
  imports_b \
  inherit_missing \
  inherit_target_language \
  kind \
  kwargs_feature \
  li_boost_shared_ptr \
  li_boost_shared_ptr_bits \
  li_carrays_cpp \
  li_std_combinations \
  li_std_vector_ptr \
  li_swigtype_inout \
  multi_import_a \
  multiple_inheritance \
  multiple_inheritance_abstract \
  multiple_inheritance_interfaces \
  multiple_inheritance_nspace \
  multiple_inheritance_shared_ptr \
  namespace_class \
  namespace_enum \
  namespace_nested \
  namespace_virtual_method \
  naturalvar_more \
  nested_class \
  nested_ignore \
  nested_scope \
  nested_workaround \
  null_pointer \
  operator_overload \
  operator_overload_break \
  overload_arrays \
  overload_copy \
  overload_method \
  overload_numeric \
  overload_polymorphic \
  overload_return_type \
  overload_subtype \
  overload_template \
  overload_template_fast \
  packageoption_c \
  pointer_reference \
  preproc_constants \
  redefined \
  refcount \
  register_par \
  rename_pcre_encoder \
  rename_simple \
  return_const_value \
  return_value_scope \
  rname \
  samename \
  smart_pointer_const \
  smart_pointer_const2 \
  smart_pointer_extend \
  smart_pointer_ignore \
  smart_pointer_inherit \
  smart_pointer_member \
  smart_pointer_multi \
  smart_pointer_multi_typedef \
  smart_pointer_namespace \
  smart_pointer_namespace2 \
  smart_pointer_not \
  smart_pointer_overload \
  smart_pointer_protected \
  smart_pointer_rename \
  smart_pointer_simple \
  smart_pointer_static \
  smart_pointer_template_const_overload \
  smart_pointer_template_defaults_overload \
  smart_pointer_templatemethods \
  smart_pointer_templatevariables \
  smart_pointer_typedef \
  special_variables \
  template_arg_scope \
  template_arg_typename \
  template_basic \
  template_const_ref \
  template_default \
  template_default_arg_overloaded_extend \
  template_default_arg_virtual_destructor \
  template_default_class_parms_typedef \
  template_default_vw \
  template_enum \
  template_explicit \
  template_extend_overload \
  template_extend_overload_2 \
  template_forward \
  template_methods \
  template_nested \
  template_ns \
  template_ns2 \
  template_ns_enum \
  template_ns_enum2 \
  template_opaque \
  template_ref_type \
  template_retvalue \
  template_specialization \
  template_specialization_defarg \
  template_specialization_enum \
  template_type_namespace \
  template_typedef_class_template \
  template_typedef_cplx5 \
  template_typedef_import \
  template_typedef_inherit \
  template_typemaps \
  template_typemaps_typedef \
  template_typemaps_typedef2 \
  template_using_directive_and_declaration_forward \
  template_whitespace \
  typedef_array_member \
  typemap_array_qualifiers \
  typemap_arrays \
  typemap_manyargs \
  typemap_ns_using \
  typemap_out_optimal \
  typemap_template_parm_typedef \
  types_directive \
  using1 \
  using2 \
  using_composition \
  using_extend \
  using_inherit \
  using_protected \
  valuewrapper \
  valuewrapper_base \
  valuewrapper_const \
  valuewrapper_opaque \
  variable_replacement \
  wallkw

# failed to compile wrapper
apply_strings \
  argout \
  arrays_dimensionless \
  autodoc \
  constant_pointers \
  contract \
  cpp_basic \
  cpp_enum \
  default_args \
  default_constructor \
  director_basic \
  director_binary_string \
  director_enum \
  director_extend \
  director_property \
  director_void \
  dynamic_cast \
  enum_ignore \
  enum_thorough \
  extend \
  funcptr_cpp \
  global_namespace \
  global_scope_types \
  global_vars \
  langobj \
  li_attribute \
  li_attribute_template \
  li_cdata_cpp \
  li_std_except \
  li_std_except_as_class \
  li_std_vector \
  li_std_vector_enum \
  li_stdint \
  li_typemaps \
  li_typemaps_apply \
  li_windows \
  long_long_apply \
  member_funcptr_galore \
  member_pointer \
  member_pointer_const \
  memberin_extend \
  mixed_types \
  mod_a \
  mod_b \
  name_warnings \
  namespace_spaces \
  namespace_typemap \
  operator_pointer_ref \
  overload_simple \
  primitive_ref \
  reference_global_vars \
  smart_pointer_const_overload \
  special_variable_macros \
  template_default_arg \
  template_rename \
  template_typedef_rec \
  typedef_funcptr \
  typedef_sizet \
  typedef_struct_cpp \
  typemap_global_scope \
  typemap_numinputs \
  typemap_variables \
  typemap_various \
  varargs \
  varargs_overload \
  virtual_poly \
  voidtest \
  wrapmacro

# failed to run swig

