
# failed to compile fortran
allprotected \
  autodoc \
  constant_pointers \
  constructor_copy \
  default_args \
  default_constructor \
  director_basic \
  director_detect \
  director_enum \
  director_frob \
  director_ignore \
  director_keywords \
  director_nested \
  director_overload \
  director_property \
  director_protected \
  director_redefined \
  enum_ignore \
  enum_scope_template \
  enum_thorough \
  evil_diamond_prop \
  extend_default \
  extend_template_method \
  extern_c \
  friends \
  global_namespace \
  li_std_vector_enum \
  mixed_types \
  multiple_inheritance_abstract \
  multiple_inheritance_interfaces \
  multiple_inheritance_nspace \
  namespace_class \
  namespace_nested \
  naturalvar_more \
  nested_scope \
  nested_workaround \
  null_pointer \
  operator_overload \
  overload_arrays \
  overload_method \
  overload_polymorphic \
  overload_return_type \
  overload_simple \
  overload_subtype \
  overload_template \
  overload_template_fast \
  preproc_constants \
  primitive_ref \
  refcount \
  return_const_value \
  samename \
  smart_pointer_const \
  smart_pointer_extend \
  smart_pointer_inherit \
  smart_pointer_member \
  smart_pointer_multi \
  smart_pointer_multi_typedef \
  smart_pointer_overload \
  smart_pointer_protected \
  smart_pointer_rename \
  smart_pointer_simple \
  smart_pointer_template_const_overload \
  smart_pointer_template_defaults_overload \
  smart_pointer_templatevariables \
  smart_pointer_typedef \
  special_variables \
  template_arg_typename \
  template_basic \
  template_default_arg \
  template_enum \
  template_explicit \
  template_extend_overload \
  template_methods \
  template_ns \
  template_ref_type \
  template_specialization_enum \
  template_typedef_inherit \
  typemap_ns_using \
  types_directive \
  using1 \
  using2 \
  using_protected \
  valuewrapper_base \
  valuewrapper_const \
  valuewrapper_opaque \
  wallkw

# failed to compile wrapper
apply_strings \
  contract \
  cpp_basic \
  cpp_enum \
  director_binary_string \
  director_extend \
  director_smartptr \
  dynamic_cast \
  extend \
  funcptr_cpp \
  global_vars \
  li_attribute \
  li_attribute_template \
  li_boost_shared_ptr \
  li_boost_shared_ptr_bits \
  li_boost_shared_ptr_template \
  li_cdata_cpp \
  li_std_combinations \
  li_std_except \
  li_std_except_as_class \
  li_std_vector \
  li_std_vector_ptr \
  member_funcptr_galore \
  member_pointer \
  member_pointer_const \
  memberin_extend \
  multiple_inheritance_shared_ptr \
  name_warnings \
  namespace_spaces \
  namespace_typemap \
  operator_pointer_ref \
  smart_pointer_const_overload \
  special_variable_macros \
  template_rename \
  template_typedef_rec \
  typedef_sizet \
  typedef_struct_cpp \
  typemap_various \
  varargs \
  varargs_overload \
  virtual_poly \
  wrapmacro

# failed to run swig

