
# failed to run swig
  

# failed to compile wrapper
  apply_signed_char \
  apply_strings \
  cpp_basic \
  director_binary_string \
  dynamic_cast \
  extend \
  li_attribute \
  li_attribute_template \
  li_cdata_cpp \
  li_std_except \
  li_std_except_as_class \
  li_windows \
  member_funcptr_galore \
  member_pointer \
  member_pointer_const \
  memberin_extend \
  namespace_spaces \
  namespace_typemap \
  operator_pointer_ref \
  smart_pointer_const_overload \
  special_variable_macros \
  template_basic \
  template_explicit \
  typedef_struct_cpp \
  typemap_various

# failed to compile fortran
  abstract_signature \
  allprotected \
  autodoc \
  constant_pointers \
  constructor_copy \
  contract \
  cpp_enum \
  default_args \
  default_constructor \
  director_basic \
  director_classes \
  director_default \
  director_detect \
  director_enum \
  director_frob \
  director_ignore \
  director_keywords \
  director_nested \
  director_overload2 \
  director_property \
  director_protected \
  director_redefined \
  enum_ignore \
  enum_scope_template \
  enum_thorough \
  evil_diamond_prop \
  extend_default \
  friends \
  fvirtual \
  global_namespace \
  global_vars \
  inherit_target_language \
  li_boost_shared_ptr \
  li_std_vector_enum \
  li_std_vector_ptr \
  mixed_types \
  multiple_inheritance \
  multiple_inheritance_abstract \
  multiple_inheritance_interfaces \
  multiple_inheritance_nspace \
  multiple_inheritance_shared_ptr \
  name_warnings \
  namespace_class \
  namespace_nested \
  naturalvar_more \
  nested_scope \
  nested_workaround \
  null_pointer \
  operator_overload \
  operator_overload_break \
  overload_arrays \
  overload_method \
  overload_polymorphic \
  overload_return_type \
  overload_simple \
  overload_subtype \
  overload_template \
  overload_template_fast \
  preproc_constants \
  primitive_ref \
  refcount \
  return_const_value \
  samename \
  smart_pointer_const \
  smart_pointer_const2 \
  smart_pointer_extend \
  smart_pointer_ignore \
  smart_pointer_inherit \
  smart_pointer_member \
  smart_pointer_multi \
  smart_pointer_multi_typedef \
  smart_pointer_namespace \
  smart_pointer_namespace2 \
  smart_pointer_not \
  smart_pointer_overload \
  smart_pointer_protected \
  smart_pointer_rename \
  smart_pointer_simple \
  smart_pointer_static \
  smart_pointer_template_const_overload \
  smart_pointer_template_defaults_overload \
  smart_pointer_templatemethods \
  smart_pointer_templatevariables \
  smart_pointer_typedef \
  special_variables \
  template_arg_typename \
  template_default_arg \
  template_enum \
  template_extend_overload \
  template_methods \
  template_ns \
  template_ref_type \
  template_specialization_enum \
  template_typedef_inherit \
  typemap_ns_using \
  types_directive \
  using1 \
  using2 \
  using_composition \
  using_extend \
  using_inherit \
  using_protected \
  valuewrapper_base \
  valuewrapper_const \
  valuewrapper_opaque \
  variable_replacement \
  virtual_poly \
  wallkw
