/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module foomod;

static import foomod_im;
static import tango.stdc.config;
static import tango.stdc.stringz;


void set_something(int x, double y) {
  foomod_im.set_something(x, y);
}

double get_something(int x) {
  auto ret = foomod_im.get_something(x);
  return ret;
}
