! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module abstract_signature
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! PUBLIC METHODS AND TYPES
 public :: abstract_foo
 public :: abstract_bar

 ! TYPES
 type, abstract :: abstract_foo
  ! These should be treated as PROTECTED data
  type(C_PTR), public :: swigptr = C_NULL_PTR
 contains
  procedure :: release => swigf_delete_abstract_foo
  procedure(swigf_abstract_foo_meth), deferred :: foo_meth
  generic :: meth => foo_meth
 end type
 type, extends(abstract_foo), abstract :: abstract_bar
 contains
  procedure :: release => swigf_delete_abstract_bar
  procedure, public :: foo_meth
  procedure, private :: meth__SWIG_1 => swigf_abstract_bar_meth__SWIG_1
  generic :: meth => meth__SWIG_1
 end type


 ! WRAPPER DECLARATIONS
 interface
subroutine swigc_delete_abstract_foo(farg1) &
bind(C, name="swigc_delete_abstract_foo")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

subroutine swigc_delete_abstract_bar(farg1) &
bind(C, name="swigc_delete_abstract_bar")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

function swigc_abstract_bar_meth__SWIG_0(farg1, farg2) &
bind(C, name="swigc_abstract_bar_meth__SWIG_0") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_abstract_bar_meth__SWIG_1(farg1, farg2, farg3) &
bind(C, name="swigc_abstract_bar_meth__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
integer(C_INT) :: fresult
end function

function swigf_abstract_foo_meth(self, meth_param) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
import :: abstract_foo
integer(C_INT) :: swigf_result
class(abstract_foo) :: self
integer(C_INT), intent(in) :: meth_param
integer(C_INT) :: fresult 
end function

 end interface


contains
 ! FORTRAN PROXY CODE
subroutine swigf_delete_abstract_foo(self)
use, intrinsic :: ISO_C_BINDING
class(abstract_foo) :: self
type(C_PTR) :: farg1 

if (.not. c_associated(self%swigptr)) return
farg1 = self%swigptr
call swigc_delete_abstract_foo(farg1)
self%swigptr = C_NULL_PTR
end subroutine

subroutine swigf_delete_abstract_bar(self)
use, intrinsic :: ISO_C_BINDING
class(abstract_bar) :: self
type(C_PTR) :: farg1 

if (.not. c_associated(self%swigptr)) return
farg1 = self%swigptr
call swigc_delete_abstract_bar(farg1)
self%swigptr = C_NULL_PTR
end subroutine

function foo_meth(self, meth_param) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swigf_result
class(abstract_bar) :: self
integer(C_INT), intent(in) :: meth_param
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigptr
farg2 = meth_param
fresult = swigc_abstract_bar_meth__SWIG_0(farg1, farg2)
swigf_result = fresult
end function

function swigf_abstract_bar_meth__SWIG_1(self, meth_param_1, meth_param_2) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swigf_result
class(abstract_bar) :: self
integer(C_INT), intent(in) :: meth_param_1
integer(C_INT), intent(in) :: meth_param_2
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 
integer(C_INT) :: farg3 

farg1 = self%swigptr
farg2 = meth_param_1
farg3 = meth_param_2
fresult = swigc_abstract_bar_meth__SWIG_1(farg1, farg2, farg3)
swigf_result = fresult
end function


end module abstract_signature
